//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioInfraccional
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historica
    {
        public Nullable<int> idFiscalizacionDetalle { get; set; }
        public Nullable<int> idFiscalizacionCheckList { get; set; }
        public string descripcionOrigen { get; set; }
        public string aftFolio { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> idFiscalizador { get; set; }
        public Nullable<int> idFiscalizacion { get; set; }
        public Nullable<int> idRolFiscalizador { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaTermino { get; set; }
        public Nullable<int> tiempoTotal { get; set; }
        public string nombreFiscalizacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> allday { get; set; }
        public Nullable<int> estadoFiscalizacionId { get; set; }
        public string estadoFiscalizacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idEntidad { get; set; }
        public Nullable<int> idChecklist { get; set; }
        public Nullable<int> idTipoFiscalizacion { get; set; }
        public string listFiscalizadores { get; set; }
        public string rutFiscalizador { get; set; }
        public string nombreFiscalizador { get; set; }
        public string listIncumplimientos { get; set; }
        public string tipoFiscalizacion { get; set; }
        public Nullable<int> anioFiscalizacion { get; set; }
        public string nombreSubMateria { get; set; }
        public string nombreMateria { get; set; }
        public string nombreAmbito { get; set; }
        public string nombreEstablecimientoLugar { get; set; }
        public string nombreRepresentante { get; set; }
        public string rutEntidad { get; set; }
        public string rutRepresentante { get; set; }
        public string nombreEntidad { get; set; }
        public string coordenadaX { get; set; }
        public string coordenadaY { get; set; }
        public string huso { get; set; }
        public string numeroIdentificador { get; set; }
        public string tipoIdentificador { get; set; }
        public string resultadoFiscalizacion { get; set; }
        public Nullable<int> idOrigen { get; set; }
        public string tipoPersona { get; set; }
        public string direccionEntidad { get; set; }
        public string comunaNombre { get; set; }
        public string regionnombre2 { get; set; }
        public Nullable<int> regionnombre3 { get; set; }
        public Nullable<int> regionnombre4 { get; set; }
        public string regionnombre5 { get; set; }
        public string regionNombre { get; set; }
        public string aftAdjunto { get; set; }
        public string pautaAdjunto { get; set; }
        public string adcAdjunto { get; set; }
        public string otroAdjunto { get; set; }
        public string nombreOficina { get; set; }
        public Nullable<int> idOficina { get; set; }
        public string regionOficinaFiscalizador { get; set; }
        public string codigoIndicador { get; set; }
        public string nombreRazonSocial { get; set; }
        public string regionFiscalizado { get; set; }
        public string comunaFiscalizado { get; set; }
        public string direccionFiscalizado { get; set; }
        public string telefonoFiscalizado { get; set; }
        public string correoFiscalizado { get; set; }
        public string usuarioCreador { get; set; }
        public Nullable<int> idTipoIdentificador { get; set; }
        public Nullable<int> RegFiscalizador { get; set; }
        public Nullable<int> ComunaFiscalizador { get; set; }
        public Nullable<int> idresultado { get; set; }
        public Nullable<int> idAmbito { get; set; }
        public Nullable<int> idMateria { get; set; }
        public Nullable<int> idSubMateria { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public string generoFiscalizado { get; set; }
        public string idAdc { get; set; }
        public string adc { get; set; }
        public string adcFolio { get; set; }
        public string numeroMuestras { get; set; }
        public string tieneMuestras { get; set; }
        public string muestraFolio { get; set; }
        public string actaCautiverio { get; set; }
        public string cautiverioFolio { get; set; }
        public string actaOtros { get; set; }
        public string otrosFolio { get; set; }
        public string nombreFiscalizado { get; set; }
        public string rutFiscalizado { get; set; }
        public Nullable<long> RowNum { get; set; }
        public string nombreEntidadReporte { get; set; }
        public string identificadorEntidadReporte { get; set; }
        public string direccionEntidadReporte { get; set; }
        public string telefonoEntidadReporte { get; set; }
        public string correoEntidadReporte { get; set; }
        public Nullable<int> idTipoRepresentanteEntidadReporte { get; set; }
        public string nombreRepresentanteEntidadReporte { get; set; }
        public string rutRepresentanteEntidadReporte { get; set; }
        public Nullable<int> idEntidadReporte { get; set; }
        public Nullable<int> subMateriaEntidadReporte { get; set; }
        public Nullable<int> comunaEntidadReporte { get; set; }
        public Nullable<int> idComuna { get; set; }
    }
}
