//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioInfraccional
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sancionatorioEDM : DbContext
    {
        public sancionatorioEDM()
            : base("name=sancionatorioEDM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SS_ADM_USUARIOS> SS_ADM_USUARIOS { get; set; }
        public virtual DbSet<SS_MAE_PROCESO> SS_MAE_PROCESO { get; set; }
        public virtual DbSet<SS_NEG_ADC> SS_NEG_ADC { get; set; }
        public virtual DbSet<SS_NEG_ADC_HITO> SS_NEG_ADC_HITO { get; set; }
        public virtual DbSet<SS_NEG_ADC_RESOLUCION> SS_NEG_ADC_RESOLUCION { get; set; }
        public virtual DbSet<SS_NEG_ADC_SENTENCIA> SS_NEG_ADC_SENTENCIA { get; set; }
        public virtual DbSet<SS_NEG_INFRACTOR> SS_NEG_INFRACTOR { get; set; }
    }
}
