//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioInfraccional
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_NEG_ADC_RESOLUCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SS_NEG_ADC_RESOLUCION()
        {
            this.SS_NEG_ADC_SENTENCIA = new HashSet<SS_NEG_ADC_SENTENCIA>();
        }
    
        public int ADR_ID { get; set; }
        public int ADR_USR_RUT { get; set; }
        public System.DateTime ADR_FECHA { get; set; }
        public System.DateTime ADR_FECHA_SIS { get; set; }
        public string ADR_TIPO_ACC { get; set; }
        public Nullable<int> ADR_USR_RUT_ACC { get; set; }
        public Nullable<System.DateTime> ADR_FECHA_ACC { get; set; }
        public Nullable<System.DateTime> ADR_FECHA_SIS_ACC { get; set; }
        public int ADR_ADH_COD { get; set; }
        public string ADR_TIPO_DECISION { get; set; }
    
        public virtual SS_ADM_USUARIOS SS_ADM_USUARIOS { get; set; }
        public virtual SS_ADM_USUARIOS SS_ADM_USUARIOS1 { get; set; }
        public virtual SS_NEG_ADC_HITO SS_NEG_ADC_HITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_NEG_ADC_SENTENCIA> SS_NEG_ADC_SENTENCIA { get; set; }
    }
}
