//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioInfraccional
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_NEG_ADC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SS_NEG_ADC()
        {
            this.SS_NEG_ADC_HITO = new HashSet<SS_NEG_ADC_HITO>();
        }
    
        public int ADC_ID { get; set; }
        public int ADC_SISTEMA_ID { get; set; }
        public int ADC_TIPO_PROCESO { get; set; }
        public int ADC_COD_ENTIDAD { get; set; }
        public int ADC_INFRACTOR { get; set; }
        public Nullable<int> ADC_COD_INFRACCION { get; set; }
        public decimal ADC_ROL { get; set; }
        public Nullable<decimal> ADC_NUMERO { get; set; }
        public Nullable<int> ADC_COD_PIEFIRMA { get; set; }
        public Nullable<System.DateTime> ADC_FECHA_AUDIENCIA { get; set; }
        public string ADC_TRANSPORTE { get; set; }
        public string ADC_DECLARACION { get; set; }
        public System.DateTime ADC_FECHA_CREACION { get; set; }
        public int ADC_USUARIO_CREADOR { get; set; }
        public Nullable<System.DateTime> ADC_ULTIMA_MODIFICACION { get; set; }
        public Nullable<int> ADC_USUARIO_MODIFICADOR { get; set; }
        public Nullable<int> ADC_ID_SUBMATERIA { get; set; }
        public Nullable<int> ADC_FIN_ID { get; set; }
        public Nullable<System.DateTime> ADC_FECHA_INGRESO { get; set; }
        public string ADC_PROCESO_FIN { get; set; }
        public int ADC_RUT_INSPECTOR { get; set; }
        public Nullable<int> ADC_RUT_SUSTANCIADOR { get; set; }
        public Nullable<int> ADC_OFICINA_USUARIO { get; set; }
        public Nullable<System.DateTime> ADC_FECHA_DENUNCIA { get; set; }
        public Nullable<decimal> ADC_NRO_FISCALIZACION { get; set; }
    
        public virtual SS_ADM_USUARIOS SS_ADM_USUARIOS { get; set; }
        public virtual SS_ADM_USUARIOS SS_ADM_USUARIOS1 { get; set; }
        public virtual SS_ADM_USUARIOS SS_ADM_USUARIOS2 { get; set; }
        public virtual SS_ADM_USUARIOS SS_ADM_USUARIOS3 { get; set; }
        public virtual SS_ADM_USUARIOS SS_ADM_USUARIOS4 { get; set; }
        public virtual SS_MAE_PROCESO SS_MAE_PROCESO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_NEG_ADC_HITO> SS_NEG_ADC_HITO { get; set; }
        public virtual SS_NEG_INFRACTOR SS_NEG_INFRACTOR { get; set; }
    }
}
