//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioInfraccional
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_NEG_ADC_HITO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SS_NEG_ADC_HITO()
        {
            this.SS_NEG_ADC_RESOLUCION = new HashSet<SS_NEG_ADC_RESOLUCION>();
        }
    
        public int ADH_COD { get; set; }
        public int ADH_ADC_ID { get; set; }
        public int ADH_COD_HITO { get; set; }
        public int ADH_RUT_USUARIO { get; set; }
        public System.DateTime ADH_FECHA { get; set; }
        public string ADH_NUM_RESOLUCION { get; set; }
        public string ADH_OBSERVACION { get; set; }
        public Nullable<System.DateTime> ADH_FECHA_HITO { get; set; }
    
        public virtual SS_ADM_USUARIOS SS_ADM_USUARIOS { get; set; }
        public virtual SS_NEG_ADC SS_NEG_ADC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_NEG_ADC_RESOLUCION> SS_NEG_ADC_RESOLUCION { get; set; }
    }
}
