//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioInfraccional
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_NEG_ADC_SENTENCIA
    {
        public int ADS_ID { get; set; }
        public int ADS_ADR_ID { get; set; }
        public int ADS_COD_TIPO_SENTENCIA { get; set; }
        public Nullable<int> ADS_COD_MEDIDA { get; set; }
        public Nullable<int> ADS_DIA_DURACION { get; set; }
        public Nullable<System.DateTime> ADS_FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> ADS_FECHA_FIN { get; set; }
        public string ADS_OBSERVACION { get; set; }
        public int ADS_USR_RUT { get; set; }
        public System.DateTime ADS_FECHA_SISTEMA { get; set; }
        public Nullable<int> ADS_TEL_ID { get; set; }
        public Nullable<int> ADS_TSU_ID { get; set; }
    
        public virtual SS_ADM_USUARIOS SS_ADM_USUARIOS { get; set; }
        public virtual SS_NEG_ADC_RESOLUCION SS_NEG_ADC_RESOLUCION { get; set; }
    }
}
