//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioInfraccional
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_NEG_INFRACTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SS_NEG_INFRACTOR()
        {
            this.SS_NEG_ADC = new HashSet<SS_NEG_ADC>();
        }
    
        public Nullable<int> IFR_COD_ACTIVIDAD { get; set; }
        public int IFR_COD { get; set; }
        public string IFR_TIPO_ID { get; set; }
        public string IFR_IDENTIFICACION { get; set; }
        public string IFR_TIPO_PERSONA { get; set; }
        public string IFR_NOMBRES { get; set; }
        public string IFR_APELLIDO_PAT { get; set; }
        public string IFR_APELLIDO_MAT { get; set; }
        public string IFR_DOMICILIO { get; set; }
        public string IFR_GENERO { get; set; }
        public string IFR_COD_COMUNA { get; set; }
        public Nullable<int> IFR_COD_PAIS { get; set; }
        public string IFR_REP_LEG_RUT { get; set; }
        public string IFR_REP_LEG_NOM { get; set; }
        public string IFR_FONO { get; set; }
        public string IFR_EMAIL { get; set; }
        public string IFR_DIR_POSTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SS_NEG_ADC> SS_NEG_ADC { get; set; }
    }
}
